name: post-release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  post_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish || github.ref }}
      - run: echo "npm_version=$(npm pkg get version | tr -d '"')" >> "$GITHUB_ENV"
      - uses: ./.github/actions/release-commenter
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag-filter: 'v\d'

          # Disable commenting for now
          # Possible limitation because we release off of main and beta branches:
          # https://github.com/apexskier/github-release-commenter#known-limitations
          comment-template: ''

          # TODO: Re-enable this after verifying that the action works as expected
          # comment-template: |
          #   🚀 This is included in version {release_link}
