name: release-canary

on:
  workflow_dispatch:
    branches:
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Canary release script
        # dry run hard-coded to true for testing and no npm token provided
        run: pnpm tsx ./scripts/publish-canary.ts
