name: build

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    paths:
      - templates/**

jobs:
  templates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template: [blank, website, ecommerce]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 25

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0

      - name: Build Website
        run: |
          cd templates/${{ matrix.template }}
          cp .env.example .env
          yarn install
          yarn build
