name: triage

on:
  issues:
    types:
      - opened
      - labeled
  issue_comment:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write

jobs:
  triage:
    name: nissuer
    if: >
      !contains(github.event.issue.labels.*.name, 'created-by: Payload team')
    runs-on: ubuntu-latest
    steps:
      - uses: balazsorban44/nissuer@1.10.0
        with:
          reproduction-comment: '.github/comments/invalid-reproduction.md'
          reproduction-blocklist: 'github.com/payloadcms/payload.*,github.com/\\w*/?$,github.com$'
          reproduction-link-section: '### Link to the code that reproduces this issue(.*)### Reproduction Steps'
          reproduction-invalid-label: 'invalid-reproduction'
          reproduction-issue-labels: 'status: needs-triage,'
